granite.build:
  name: msc-task
  targets:
    msc-task:
      environment_uri: space://environments/bluevela
      steps:
        - step_uri: "space://steps/custom_code_lsf"
          config:
            compute_config:
              num_nodes: 1
              num_gpus_per_node: 1
              num_cpus_per_node: 4
              total_memory_per_node: 32Gi
            byoc_config:
              github_url: "github.com/dhavalsalwala/mellea-skills-compiler"
              github_ref: "msc-bluevela"
              conda_lockfile_path: "bluevela/conda-lock.yml"
              setup_command: >-
                pip install --no-cache-dir --only-binary=:all: vllm &&
                pip install -r bluevela/requirements.txt
              dependency_files:
                - "bluevela/conda-lock.yml"
                - "bluevela/requirements.txt"
              start_command: >-
                export PYTHONPATH=$REPO_ROOT/src &&
                bash bluevela/run.sh
              dir_to_save: "."
              output_name: "msc-output"
